SELECT PRIVILEGE FROM DBA_SYS_PRIVS WHERE GRANTEE = 'CONNECT';

SELECT PRIVILEGE 
FROM DBA_SYS_PRIVS 
WHERE GRANTEE = 'RESOURCE';

ALTER USER CONTA QUOTA UNLIMITED ON USERS;


SELECT OWNER, ABLE_NAME, TABLESPACE_NAME, *
FROM ALL_TABLES
WHERE TABLE_NAME = 'DEMO';

SELECT SEGMENT_NAME, SEGMENT_TYPE, 
       TABLESPACE_NAME, BYTES, BLOCKS, EXTENTS
FROM USER_SEGMENTS
WHERE SEGMENT_NAME = 'DEMO';

-- EJERCICIO 01

-- USER SQL
CREATE USER "ECORONEL" IDENTIFIED BY "ecoronel"  
DEFAULT TABLESPACE "USERS" 
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "ECORONEL" QUOTA UNLIMITED ON "USERS";

-- ROLES
GRANT "CONNECT", "RESOURCE"  TO "ECORONEL" ;



